<?php
    $autousate = [
        [
            'id' => '101010',
            'modello'=> 'C3',
            'marca'=> 'Citroen',
            'colore' => 'rossa',
            'porte'=> 5,
            'km'=> 12000,
            'carburante'=> 'GPL',
            'anno'=> 2016,
            'cavalli'=> 65,
            'stato'=> 'buone condizioni',
            'numtelaio'=> 12121212,
            'descrizione'=> 'Ciao',
            'optional'=> '',
            'prezzo' => 5000,
        ],
        [
            'id' => '202020',
            'modello'=> 'C5',
            'marca'=> 'Citroen',
            'colore' => 'verde',
            'porte'=> 5,
            'km'=> 16000,
            'carburante'=> 'diesel',
            'anno'=> 2018,
            'cavalli'=> 85,
            'stato'=> 'ottime condizioni',
            'numtelaio'=> 15151513,
            'descrizione'=> 'Ciao',
            'optional'=> 'Aria condizionata, autoradio',
            'prezzo' => 8000,
        ],
        [
            'id' => '303030',
            'modello'=> 'Giulietta',
            'marca'=> 'Alfa Romeo',
            'colore' => 'rossa',
            'porte'=> 5,
            'km'=> 50000,
            'carburante'=> 'diesel',
            'anno'=> 2017,
            'cavalli'=> 95,
            'stato'=> 'ottime condizioni',
            'numtelaio'=> 1467890,
            'descrizione'=> 'Ciao',
            'optional'=> 'Aria condizionata, autoradio, Bluetooth',
            'prezzo' => 10000,
        ],
        [
            'id' => '404040',
            'modello'=> 'Fiat',
            'marca'=> 'Panda',
            'colore' => 'Verde Acqua scolorito',
            'porte'=> 3,
            'km'=> 400000,
            'carburante'=> 'benzina',
            'anno'=> 1990,
            'cavalli'=> 35,
            'stato'=> 'indistruttibile',
            'numtelaio'=> 22233456,
            'descrizione'=> 'Ciao',
            'optional'=> '',
            'prezzo' => 500.55,
        ],
        [
            'id' => '505050',
            'modello'=> 'Fiat',
            'marca'=> 'Tipo',
            'colore' => '',
            'porte'=> 5,
            'km'=> 40000,
            'carburante'=> 'benzina',
            'anno'=> 2008,
            'cavalli'=> 65,
            'stato'=> 'buono',
            'numtelaio'=> 247833456,
            'descrizione'=> 'Ciao',
            'optional'=> '',
            'prezzo' => 5099.99,
        ],
    ]
?>